-- Script de création de la base RH
-- Tables : employees, evaluations, sondages
-- SGBD : PostgreSQL

-- Suppression si existant
DROP TABLE IF EXISTS sondages CASCADE;
DROP TABLE IF EXISTS evaluations CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS predictions CASCADE;

-- Table principale : employees
CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age SMALLINT,
    genre VARCHAR(10),
    revenu_mensuel NUMERIC(10, 2),
    statut_marital VARCHAR(20),
    departement VARCHAR(50),
    poste VARCHAR(50),
    nombre_experiences_precedentes SMALLINT,
    nombre_heures_travailless SMALLINT,
    annee_experience_totale SMALLINT,
    annees_dans_l_entreprise SMALLINT,
    annees_dans_le_poste_actuel SMALLINT
);

-- Table evaluations
CREATE TABLE evaluations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER,
    eval_number VARCHAR(10),
    satisfaction_employee_environnement SMALLINT,
    note_evaluation_precedente SMALLINT,
    niveau_hierarchique_poste SMALLINT,
    satisfaction_employee_nature_travail SMALLINT,
    satisfaction_employee_equipe SMALLINT,
    satisfaction_employee_equilibre_pro_perso SMALLINT,
    note_evaluation_actuelle SMALLINT,
    heure_supplementaires VARCHAR(10),
    augementation_salaire_precedente VARCHAR(10),
    CONSTRAINT fk_evaluations_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

-- Table sondages
CREATE TABLE sondages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_sondage INTEGER,
    employee_id INTEGER,
    a_quitte_l_entreprise VARCHAR(50),
    nombre_participation_pee SMALLINT,
    nb_formations_suivies SMALLINT,
    nombre_employee_sous_responsabilite SMALLINT,
    distance_domicile_travail SMALLINT,
    niveau_education SMALLINT,
    domaine_etude VARCHAR(50),
    ayant_enfants VARCHAR(50),
    frequence_deplacement VARCHAR(30),
    annees_depuis_la_derniere_promotion SMALLINT,
    annes_sous_responsable_actuel SMALLINT,
    CONSTRAINT fk_sondages_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE predictions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_data JSONB NOT NULL,
    probability DOUBLE PRECISION NOT NULL,
    prediction SMALLINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_evaluations_employee_id ON evaluations (employee_id);
CREATE INDEX idx_sondages_employee_id ON sondages (employee_id);