name: Train and Deploy

on:
  push:
    branches: [ feature/deploy ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        with:
          lfs: true
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Copy .env file
        run: cp .env.example .env

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run python -m pytest tests/test_main.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        with:
          fetch-depth: 0
          lfs: true
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ env.HF_SPACE_ID }}
        run: |
          git remote add space https://user:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE_ID
          git push --force space HEAD:main